// dash-qt amount formatting and parsing in Swift (QT-020, QT-036, QT-039, QT-152).
//
// Port of rust/crates/dw-units, which reproduces dash-qt's `BitcoinUnits`
// and `GUIUtil::formatAmount`. testdata/amount_format.json holds the golden
// vectors (generated by running the dash-qt code) that both implementations
// are tested against.
//
// Rules:
// - The thousands separator is U+2009 THIN SPACE; the decimal mark is ".".
// - `floored` and `gui(truncate:)` cut decimals; they never round.
// - Parsing ignores spaces and thin spaces and accepts one leading sign.
import Foundation
import WalletRuntime

extension DisplayUnit {
    /// Duffs per one of this unit.
    public var factor: Int64 {
        switch self {
        case .dash: 100_000_000
        case .milliDash: 100_000
        case .microDash: 100
        case .duffs: 1
        }
    }

    /// Decimals shown for this unit.
    public var decimals: Int {
        switch self {
        case .dash: 8
        case .milliDash: 5
        case .microDash: 2
        case .duffs: 0
        }
    }

    /// dash-qt's `BitcoinUnits::name`. Every network except mainnet uses the
    /// `t` names. μ is U+03BC.
    public func name(on network: DashNetwork) -> String {
        let test = network != .mainnet
        switch self {
        case .dash: return test ? "tDASH" : "DASH"
        case .milliDash: return test ? "mtDASH" : "mDASH"
        case .microDash: return test ? "\u{3bc}tDASH" : "\u{3bc}DASH"
        case .duffs: return test ? "tduffs" : "duffs"
        }
    }
}

/// `AmountFormatting` implemented in Swift with dash-qt's rules for one
/// network. The composition root may use it or the engine-backed adapter;
/// both produce the strings in testdata/amount_format.json.
public final class AmountFormatter: AmountFormatting {
    public static let thinSpace: Character = "\u{2009}"
    /// Largest valid amount, 21 million DASH (`MAX_MONEY`).
    public static let maxMoney = Amount(duffs: 21_000_000 * Amount.duffsPerDash)
    /// Width `justify` pads the integer part plus decimals to.
    private static let maxDigits = 16
    /// Longest digit string `parse` accepts after padding the decimals.
    private static let maxParseLength = 18

    public let network: DashNetwork

    public init(network: DashNetwork) {
        self.network = network
    }

    public func unitName(_ unit: DisplayUnit) -> String {
        unit.name(on: network)
    }

    public func format(_ amount: Amount, unit: DisplayUnit, style: AmountStyle) -> String {
        let name = unit.name(on: network)
        switch style {
        case .plain(let plus, let separators):
            return Self.plain(amount.duffs, unit: unit, plusSign: plus, separators: separators, justify: false)
        case .withUnit(let plus, let separators):
            return Self.plain(amount.duffs, unit: unit, plusSign: plus, separators: separators, justify: false)
                + " " + name
        case .floored(let plus, let separators, let digits):
            var text = Self.plain(amount.duffs, unit: unit, plusSign: plus, separators: separators, justify: false)
            let chop = unit.decimals - max(0, digits)
            if chop > 0 {
                text = String(text.dropLast(chop))
            }
            return text + " " + name
        case .privacy(let separators, let hidden):
            let value = hidden
                ? Self.plain(0, unit: unit, plusSign: false, separators: separators, justify: true)
                    .replacingOccurrences(of: "0", with: "#")
                : Self.plain(amount.duffs, unit: unit, plusSign: false, separators: separators, justify: true)
            return value + " " + name
        case .gui(let signed, let truncate):
            var text = Self.plain(amount.duffs, unit: unit, plusSign: signed, separators: .always, justify: false)
            if let truncate, let dot = text.firstIndex(of: ".") {
                if truncate <= 0 {
                    text = String(text[..<dot])
                } else {
                    let afterDot = text.index(after: dot)
                    if text.distance(from: afterDot, to: text.endIndex) > truncate {
                        text = String(text[..<text.index(afterDot, offsetBy: truncate)])
                    }
                }
            }
            return text + " " + name
        }
    }

    public func parse(_ text: String, unit: DisplayUnit) throws(ServiceError) -> Amount {
        guard let duffs = Self.parseDuffs(text, unit: unit) else {
            throw ServiceError(code: .unitsUnparsable, detail: "unparsable amount")
        }
        return Amount(duffs: duffs)
    }

    /// `BitcoinUnits::format`: the number without a unit name. `justify`
    /// left-pads the integer part with spaces to `16 - decimals` characters
    /// before separators are inserted, as dash-qt does.
    public static func plain(
        _ duffs: Int64, unit: DisplayUnit, plusSign: Bool, separators: AmountSeparators, justify: Bool
    ) -> String {
        let coin = UInt64(unit.factor)
        let decimals = unit.decimals
        let magnitude = duffs.magnitude
        var integer = Array(String(magnitude / coin))
        if justify {
            let width = maxDigits - decimals
            if integer.count < width {
                integer = Array(repeating: " ", count: width - integer.count) + integer
            }
        }
        let size = integer.count
        let separate: Bool
        switch separators {
        case .always: separate = true
        case .standard: separate = size > 4
        case .never: separate = false
        }
        if separate {
            // Positions count from the right on the unmodified length, so an
            // insert never shifts the positions still to come (dash-qt's loop).
            var i = 3
            while i < size {
                integer.insert(thinSpace, at: size - i)
                i += 3
            }
        }
        var out = ""
        if duffs < 0 {
            out.append("-")
        } else if plusSign && duffs > 0 {
            out.append("+")
        }
        out.append(String(integer))
        if decimals > 0 {
            let remainder = String(magnitude % coin)
            out.append(".")
            out.append(String(repeating: "0", count: decimals - remainder.count))
            out.append(remainder)
        }
        return out
    }

    /// `BitcoinUnits::parse`: `nil` exactly where dash-qt's parser fails.
    public static func parseDuffs(_ text: String, unit: DisplayUnit) -> Int64? {
        guard !text.isEmpty else { return nil }
        let cleaned = String(text.unicodeScalars.filter { $0 != " " && $0 != "\u{2009}" }.map(Character.init))
        let parts = cleaned.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count <= 2 else { return nil }
        let decimals = parts.count == 2 ? String(parts[1]) : ""
        let decimalsLength = decimals.utf16.count
        guard decimalsLength <= unit.decimals else { return nil }
        let padded = String(parts[0]) + decimals + String(repeating: "0", count: unit.decimals - decimalsLength)
        guard padded.utf16.count <= maxParseLength else { return nil }
        return qtToLongLong(padded)
    }

    /// `QString::toLongLong` for at most 18 UTF-16 units: Unicode White_Space
    /// trimmed at both ends, then one optional sign and one or more ASCII
    /// digits. Eighteen digits cannot overflow `Int64`.
    private static func qtToLongLong(_ text: String) -> Int64? {
        var scalars = Substring(text).unicodeScalars[...]
        while let first = scalars.first, first.properties.isWhitespace { scalars.removeFirst() }
        while let last = scalars.last, last.properties.isWhitespace { scalars.removeLast() }
        var negative = false
        if let sign = scalars.first, sign == "+" || sign == "-" {
            negative = sign == "-"
            scalars.removeFirst()
        }
        guard !scalars.isEmpty, scalars.allSatisfy({ $0.isASCII && ("0"..."9").contains($0) }) else { return nil }
        guard let magnitude = Int64(String(String.UnicodeScalarView(scalars))) else { return nil }
        return negative ? -magnitude : magnitude
    }
}
