// 1:1 mirrors of simple FFI enums. Generated by a one-off script; edit by hand.
import DashWalletCore

/// dash-spv sync phases, in the order they run.
public enum SyncPhase: Sendable, Hashable, CaseIterable {
    case headers, filterHeaders, filters, masternodes

    init(_ ffi: DashWalletCore.SyncPhase) {
        switch ffi {
        case .headers: self = .headers
        case .filterHeaders: self = .filterHeaders
        case .filters: self = .filters
        case .masternodes: self = .masternodes
        }
    }

    var ffi: DashWalletCore.SyncPhase {
        switch self {
        case .headers: .headers
        case .filterHeaders: .filterHeaders
        case .filters: .filters
        case .masternodes: .masternodes
        }
    }
}

/// Vault lock state (DESIGN-opus §1.8).
public enum VaultLockState: Sendable, Hashable, CaseIterable {
    case noVault, noKeys, unencrypted, locked, unlockedMixingOnly, unlocked

    init(_ ffi: DashWalletCore.VaultLockState) {
        switch ffi {
        case .noVault: self = .noVault
        case .noKeys: self = .noKeys
        case .unencrypted: self = .unencrypted
        case .locked: self = .locked
        case .unlockedMixingOnly: self = .unlockedMixingOnly
        case .unlocked: self = .unlocked
        }
    }

    var ffi: DashWalletCore.VaultLockState {
        switch self {
        case .noVault: .noVault
        case .noKeys: .noKeys
        case .unencrypted: .unencrypted
        case .locked: .locked
        case .unlockedMixingOnly: .unlockedMixingOnly
        case .unlocked: .unlocked
        }
    }
}

/// What `unlock` enables; `mixingOnly` is dash-qt "Unlock for mixing only" (QT-112).
public enum UnlockScope: Sendable, Hashable, CaseIterable {
    case full, mixingOnly

    init(_ ffi: DashWalletCore.UnlockScope) {
        switch ffi {
        case .full: self = .full
        case .mixingOnly: self = .mixingOnly
        }
    }

    var ffi: DashWalletCore.UnlockScope {
        switch self {
        case .full: .full
        case .mixingOnly: .mixingOnly
        }
    }
}

/// BIP39 word lists.
public enum MnemonicLanguage: Sendable, Hashable, CaseIterable {
    case english, chineseSimplified, chineseTraditional, czech, french, italian, japanese, korean, portuguese, spanish

    init(_ ffi: DashWalletCore.MnemonicLanguage) {
        switch ffi {
        case .english: self = .english
        case .chineseSimplified: self = .chineseSimplified
        case .chineseTraditional: self = .chineseTraditional
        case .czech: self = .czech
        case .french: self = .french
        case .italian: self = .italian
        case .japanese: self = .japanese
        case .korean: self = .korean
        case .portuguese: self = .portuguese
        case .spanish: self = .spanish
        }
    }

    var ffi: DashWalletCore.MnemonicLanguage {
        switch self {
        case .english: .english
        case .chineseSimplified: .chineseSimplified
        case .chineseTraditional: .chineseTraditional
        case .czech: .czech
        case .french: .french
        case .italian: .italian
        case .japanese: .japanese
        case .korean: .korean
        case .portuguese: .portuguese
        case .spanish: .spanish
        }
    }
}

/// BIP39 checksum result; `coreOnly` passes only Dash Core's weak check (QT-104).
public enum MnemonicChecksum: Sendable, Hashable, CaseIterable {
    case valid, coreOnly, invalid

    init(_ ffi: DashWalletCore.MnemonicChecksum) {
        switch ffi {
        case .valid: self = .valid
        case .coreOnly: self = .coreOnly
        case .invalid: self = .invalid
        }
    }

    var ffi: DashWalletCore.MnemonicChecksum {
        switch self {
        case .valid: .valid
        case .coreOnly: .coreOnly
        case .invalid: .invalid
        }
    }
}

/// BIP44 chain of an address.
public enum AddressChain: Sendable, Hashable, CaseIterable {
    case receiving, change

    init(_ ffi: DashWalletCore.AddressChain) {
        switch ffi {
        case .receiving: self = .receiving
        case .change: self = .change
        }
    }

    var ffi: DashWalletCore.AddressChain {
        switch self {
        case .receiving: .receiving
        case .change: .change
        }
    }
}

/// Address-book tab: someone else's address (`send`) or one of ours (`receive`).
public enum AddressPurpose: Sendable, Hashable, CaseIterable {
    case send, receive

    init(_ ffi: DashWalletCore.AddressPurpose) {
        switch ffi {
        case .send: self = .send
        case .receive: self = .receive
        }
    }

    var ffi: DashWalletCore.AddressPurpose {
        switch self {
        case .send: .send
        case .receive: .receive
        }
    }
}

/// History sort order.
public enum HistorySort: Sendable, Hashable, CaseIterable {
    case newestFirst, oldestFirst, amountDescending, amountAscending

    init(_ ffi: DashWalletCore.HistorySort) {
        switch ffi {
        case .newestFirst: self = .newestFirst
        case .oldestFirst: self = .oldestFirst
        case .amountDescending: self = .amountDescending
        case .amountAscending: self = .amountAscending
        }
    }

    var ffi: DashWalletCore.HistorySort {
        switch self {
        case .newestFirst: .newestFirst
        case .oldestFirst: .oldestFirst
        case .amountDescending: .amountDescending
        case .amountAscending: .amountAscending
        }
    }
}

/// Watch-only filter of the history (QT-089).
public enum WatchOnlyFilter: Sendable, Hashable, CaseIterable {
    case all, yes, no

    init(_ ffi: DashWalletCore.WatchOnlyFilter) {
        switch ffi {
        case .all: self = .all
        case .yes: self = .yes
        case .no: self = .no
        }
    }

    var ffi: DashWalletCore.WatchOnlyFilter {
        switch self {
        case .all: .all
        case .yes: .yes
        case .no: .no
        }
    }
}

/// dash-qt display unit (QT-020).
public enum DisplayUnit: Sendable, Hashable, CaseIterable {
    case dash, milliDash, microDash, duffs

    init(_ ffi: DashWalletCore.DisplayUnit) {
        switch ffi {
        case .dash: self = .dash
        case .milliDash: self = .milliDash
        case .microDash: self = .microDash
        case .duffs: self = .duffs
        }
    }

    var ffi: DashWalletCore.DisplayUnit {
        switch self {
        case .dash: .dash
        case .milliDash: .milliDash
        case .microDash: .microDash
        case .duffs: .duffs
        }
    }
}

/// dash-qt transaction record type, in dash-qt's order (QT-086).
public enum TxType: Sendable, Hashable, CaseIterable {
    case other, generated, sendToAddress, sendToOther, recvWithAddress, recvFromOther, sendToSelf, recvWithCoinJoin, coinJoinMixing, coinJoinCollateralPayment, coinJoinMakeCollaterals, coinJoinCreateDenominations, coinJoinSend, platformTransfer, dustReceive, dataTransaction, masternodeRegistration, masternodeUpdate, assetLock

    init(_ ffi: DashWalletCore.TxType) {
        switch ffi {
        case .other: self = .other
        case .generated: self = .generated
        case .sendToAddress: self = .sendToAddress
        case .sendToOther: self = .sendToOther
        case .recvWithAddress: self = .recvWithAddress
        case .recvFromOther: self = .recvFromOther
        case .sendToSelf: self = .sendToSelf
        case .recvWithCoinJoin: self = .recvWithCoinJoin
        case .coinJoinMixing: self = .coinJoinMixing
        case .coinJoinCollateralPayment: self = .coinJoinCollateralPayment
        case .coinJoinMakeCollaterals: self = .coinJoinMakeCollaterals
        case .coinJoinCreateDenominations: self = .coinJoinCreateDenominations
        case .coinJoinSend: self = .coinJoinSend
        case .platformTransfer: self = .platformTransfer
        case .dustReceive: self = .dustReceive
        case .dataTransaction: self = .dataTransaction
        case .masternodeRegistration: self = .masternodeRegistration
        case .masternodeUpdate: self = .masternodeUpdate
        case .assetLock: self = .assetLock
        }
    }

    var ffi: DashWalletCore.TxType {
        switch self {
        case .other: .other
        case .generated: .generated
        case .sendToAddress: .sendToAddress
        case .sendToOther: .sendToOther
        case .recvWithAddress: .recvWithAddress
        case .recvFromOther: .recvFromOther
        case .sendToSelf: .sendToSelf
        case .recvWithCoinJoin: .recvWithCoinJoin
        case .coinJoinMixing: .coinJoinMixing
        case .coinJoinCollateralPayment: .coinJoinCollateralPayment
        case .coinJoinMakeCollaterals: .coinJoinMakeCollaterals
        case .coinJoinCreateDenominations: .coinJoinCreateDenominations
        case .coinJoinSend: .coinJoinSend
        case .platformTransfer: .platformTransfer
        case .dustReceive: .dustReceive
        case .dataTransaction: .dataTransaction
        case .masternodeRegistration: .masternodeRegistration
        case .masternodeUpdate: .masternodeUpdate
        case .assetLock: .assetLock
        }
    }
}

/// iOS history filter category (IOS-028).
public enum TxCategory: Sendable, Hashable, CaseIterable {
    case sent, received, reward, masternode, internalTransfer, coinJoin, platform, other

    init(_ ffi: DashWalletCore.TxCategory) {
        switch ffi {
        case .sent: self = .sent
        case .received: self = .received
        case .reward: self = .reward
        case .masternode: self = .masternode
        case .internalTransfer: self = .internalTransfer
        case .coinJoin: self = .coinJoin
        case .platform: self = .platform
        case .other: self = .other
        }
    }

    var ffi: DashWalletCore.TxCategory {
        switch self {
        case .sent: .sent
        case .received: .received
        case .reward: .reward
        case .masternode: .masternode
        case .internalTransfer: .internalTransfer
        case .coinJoin: .coinJoin
        case .platform: .platform
        case .other: .other
        }
    }
}

/// dash-qt transaction status.
public enum TxStatusKind: Sendable, Hashable, CaseIterable {
    case unconfirmed, confirming, confirmed, conflicted, abandoned, immature, notAccepted

    init(_ ffi: DashWalletCore.TxStatusKind) {
        switch ffi {
        case .unconfirmed: self = .unconfirmed
        case .confirming: self = .confirming
        case .confirmed: self = .confirmed
        case .conflicted: self = .conflicted
        case .abandoned: self = .abandoned
        case .immature: self = .immature
        case .notAccepted: self = .notAccepted
        }
    }

    var ffi: DashWalletCore.TxStatusKind {
        switch self {
        case .unconfirmed: .unconfirmed
        case .confirming: .confirming
        case .confirmed: .confirmed
        case .conflicted: .conflicted
        case .abandoned: .abandoned
        case .immature: .immature
        case .notAccepted: .notAccepted
        }
    }
}

/// Thousands separators: `standard` = only when the integer part has more than four digits.
public enum Separators: Sendable, Hashable, CaseIterable {
    case never, standard, always

    init(_ ffi: DashWalletCore.Separators) {
        switch ffi {
        case .never: self = .never
        case .standard: self = .standard
        case .always: self = .always
        }
    }

    var ffi: DashWalletCore.Separators {
        switch self {
        case .never: .never
        case .standard: .standard
        case .always: .always
        }
    }
}
