//! testdata/governance_objects.json: governance object hashes as dashd v24
//! computes them (`gobject prepare` puts the hash in the collateral's
//! `OP_RETURN`), generated by testdata/oracle/dashd/gen_governance_objects.py.

use dashcore::blockdata::opcodes::all::OP_RETURN;
use dashcore::blockdata::script::Builder;
use dw_governance::object::{GovernanceObject, display_hex};
use dw_governance::proposal::{format_money, parse_proposal};

fn cases() -> Vec<serde_json::Value> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../testdata/governance_objects.json"
    );
    let doc: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).expect("golden file")).unwrap();
    doc["cases"].as_array().unwrap().clone()
}

#[test]
fn test_qt_132_object_hashes_equal_dashd() {
    let cases = cases();
    assert!(cases.len() >= 4);
    for c in cases {
        let data = hex::decode(c["data_hex"].as_str().unwrap()).unwrap();
        assert_eq!(data, c["data"].as_str().unwrap().as_bytes());
        let obj = GovernanceObject::new_proposal(
            c["revision"].as_i64().unwrap() as i32,
            c["time"].as_i64().unwrap(),
            data,
        );
        let hash = obj.hash();
        assert_eq!(display_hex(&hash), c["object_hash"].as_str().unwrap());
        // The collateral output script the engine builds for this hash.
        let script = Builder::new()
            .push_opcode(OP_RETURN)
            .push_slice(hash)
            .into_script();
        assert_eq!(
            hex::encode(script.as_bytes()),
            c["collateral_script"].as_str().unwrap()
        );
        assert_eq!(c["check"]["Object status"], "OK");
    }
}

#[test]
fn test_qt_132_amounts_round_trip_through_core_format_money() {
    for c in cases() {
        let text = c["data"].as_str().unwrap();
        let p = parse_proposal(text.as_bytes()).unwrap();
        let amount = format_money(p.payment_amount.unwrap());
        assert!(
            text.contains(&format!("\"payment_amount\":{amount},")),
            "{amount} not in {text}"
        );
    }
}
