// Generates testdata/coinjoin_progress.json: dash-qt's CoinJoin progress
// (QT-042) computed by the arithmetic of OverviewPage::updateCoinJoinProgress,
// src/qt/overviewpage.cpp at Dash Core v24.0.0-rc.2, copied line for line
// below (float parts, ceilf, cap at 100). The wallet calls are replaced by
// the vector's inputs.
//
//   c++ -std=c++17 -O0 -o /tmp/cjgen testdata/oracle/coinjoin_progress_gen.cpp
//   /tmp/cjgen > testdata/coinjoin_progress.json
#include <cmath>
#include <cstdint>
#include <cstdio>

typedef int64_t CAmount;
static const CAmount COIN = 100000000;

struct Vec {
    const char* name;
    CAmount balance, anonymizable, anonymized, denominated, normalized;
    int rounds, target;
};

int main()
{
    const Vec vecs[] = {
        {"zero_balance", 0, 0, 0, 0, 0, 4, 1000},
        {"nothing_mixed_yet", 500000000, 500000000, 0, 0, 0, 4, 1000},
        {"half_denominated", 500000000, 500000000, 0, 250000000, 0, 4, 1000},
        {"fully_denominated_no_rounds", 200020000, 200020000, 0, 200020000, 0, 4, 1000},
        {"partially_mixed_two_of_four", 200020000, 200020000, 0, 200020000, 100010000, 4, 1000},
        {"some_fully_mixed", 300030000, 200020000, 100010000, 300030000, 200020000, 4, 1000},
        {"all_fully_mixed", 300030000, 0, 300030000, 300030000, 300030000, 4, 1000},
        {"target_caps_max", 5000000000, 4000000000, 1000000000, 3000000000, 1500000000, 4, 20},
        {"rounds_two", 110001100, 110001100, 0, 110001100, 55000550, 2, 1000},
        {"rounds_sixteen", 110001100, 100001000, 10000100, 110001100, 30000000, 16, 1000},
        {"odd_values", 123456789, 98765432, 1234567, 87654321, 4321234, 5, 1000},
        {"tiny_wallet", 140001, 140001, 0, 100001, 0, 4, 1000},
    };
    std::printf("{\n  \"source\": \"OverviewPage::updateCoinJoinProgress, src/qt/overviewpage.cpp, Dash Core v24.0.0-rc.2; generated by testdata/oracle/coinjoin_progress_gen.cpp\",\n  \"vectors\": [\n");
    const size_t n = sizeof(vecs) / sizeof(vecs[0]);
    for (size_t i = 0; i < n; ++i) {
        const Vec& v = vecs[i];
        float progress = 0, denomPart = 0, anonNormPart = 0, anonFullPart = 0;
        CAmount nMaxToAnonymize = v.anonymizable + v.anonymized;
        if (nMaxToAnonymize > v.target * COIN) nMaxToAnonymize = v.target * COIN;
        if (v.balance != 0 && nMaxToAnonymize != 0) {
            // --- verbatim from overviewpage.cpp ---
            CAmount denominatedBalance = v.denominated;
            denomPart = (float)denominatedBalance / nMaxToAnonymize;
            denomPart = denomPart > 1 ? 1 : denomPart;
            denomPart *= 100;

            anonNormPart = (float)v.normalized / nMaxToAnonymize;
            anonNormPart = anonNormPart > 1 ? 1 : anonNormPart;
            anonNormPart *= 100;

            anonFullPart = (float)v.anonymized / nMaxToAnonymize;
            anonFullPart = anonFullPart > 1 ? 1 : anonFullPart;
            anonFullPart *= 100;

            float denomWeight = 1;
            float anonNormWeight = v.rounds;
            float anonFullWeight = 2;
            float fullWeight = denomWeight + anonNormWeight + anonFullWeight;
            float denomPartCalc = ceilf((denomPart * denomWeight / fullWeight) * 100) / 100;
            float anonNormPartCalc = ceilf((anonNormPart * anonNormWeight / fullWeight) * 100) / 100;
            float anonFullPartCalc = ceilf((anonFullPart * anonFullWeight / fullWeight) * 100) / 100;
            progress = denomPartCalc + anonNormPartCalc + anonFullPartCalc;
            if(progress >= 100) progress = 100;
            // --- end verbatim ---
        }
        std::printf("    {\"name\": \"%s\", \"balance\": %lld, \"anonymizable\": %lld, \"anonymized\": %lld, "
                    "\"denominated\": %lld, \"normalized_anonymized\": %lld, \"rounds\": %d, \"target_dash\": %d, "
                    "\"overall\": %.9g, \"denominated_percent\": %.9g, \"partially_mixed_percent\": %.9g, "
                    "\"mixed_percent\": %.9g}%s\n",
                    v.name, (long long)v.balance, (long long)v.anonymizable, (long long)v.anonymized,
                    (long long)v.denominated, (long long)v.normalized, v.rounds, v.target,
                    progress, denomPart, anonNormPart, anonFullPart, i + 1 < n ? "," : "");
    }
    std::printf("  ]\n}\n");
    return 0;
}
