// 1:1 conversions between DashKit enums and the WalletRuntime contract
// enums of the same name. Generated by a one-off script; edit by hand.
import DashKit

extension SyncPhase {
    init(_ kit: DashKit.SyncPhase) {
        switch kit {
        case .headers: self = .headers
        case .filterHeaders: self = .filterHeaders
        case .filters: self = .filters
        case .masternodes: self = .masternodes
        }
    }

    var kit: DashKit.SyncPhase {
        switch self {
        case .headers: .headers
        case .filterHeaders: .filterHeaders
        case .filters: .filters
        case .masternodes: .masternodes
        }
    }
}

extension VaultLockState {
    init(_ kit: DashKit.VaultLockState) {
        switch kit {
        case .noVault: self = .noVault
        case .noKeys: self = .noKeys
        case .unencrypted: self = .unencrypted
        case .locked: self = .locked
        case .unlockedMixingOnly: self = .unlockedMixingOnly
        case .unlocked: self = .unlocked
        }
    }

    var kit: DashKit.VaultLockState {
        switch self {
        case .noVault: .noVault
        case .noKeys: .noKeys
        case .unencrypted: .unencrypted
        case .locked: .locked
        case .unlockedMixingOnly: .unlockedMixingOnly
        case .unlocked: .unlocked
        }
    }
}

extension UnlockScope {
    init(_ kit: DashKit.UnlockScope) {
        switch kit {
        case .full: self = .full
        case .mixingOnly: self = .mixingOnly
        }
    }

    var kit: DashKit.UnlockScope {
        switch self {
        case .full: .full
        case .mixingOnly: .mixingOnly
        }
    }
}

extension MnemonicLanguage {
    init(_ kit: DashKit.MnemonicLanguage) {
        switch kit {
        case .english: self = .english
        case .chineseSimplified: self = .chineseSimplified
        case .chineseTraditional: self = .chineseTraditional
        case .czech: self = .czech
        case .french: self = .french
        case .italian: self = .italian
        case .japanese: self = .japanese
        case .korean: self = .korean
        case .portuguese: self = .portuguese
        case .spanish: self = .spanish
        }
    }

    var kit: DashKit.MnemonicLanguage {
        switch self {
        case .english: .english
        case .chineseSimplified: .chineseSimplified
        case .chineseTraditional: .chineseTraditional
        case .czech: .czech
        case .french: .french
        case .italian: .italian
        case .japanese: .japanese
        case .korean: .korean
        case .portuguese: .portuguese
        case .spanish: .spanish
        }
    }
}

extension MnemonicChecksum {
    init(_ kit: DashKit.MnemonicChecksum) {
        switch kit {
        case .valid: self = .valid
        case .coreOnly: self = .coreOnly
        case .invalid: self = .invalid
        }
    }

    var kit: DashKit.MnemonicChecksum {
        switch self {
        case .valid: .valid
        case .coreOnly: .coreOnly
        case .invalid: .invalid
        }
    }
}

extension AddressChain {
    init(_ kit: DashKit.AddressChain) {
        switch kit {
        case .receiving: self = .receiving
        case .change: self = .change
        }
    }

    var kit: DashKit.AddressChain {
        switch self {
        case .receiving: .receiving
        case .change: .change
        }
    }
}

extension AddressPurpose {
    init(_ kit: DashKit.AddressPurpose) {
        switch kit {
        case .send: self = .send
        case .receive: self = .receive
        }
    }

    var kit: DashKit.AddressPurpose {
        switch self {
        case .send: .send
        case .receive: .receive
        }
    }
}

extension HistorySort {
    init(_ kit: DashKit.HistorySort) {
        switch kit {
        case .newestFirst: self = .newestFirst
        case .oldestFirst: self = .oldestFirst
        case .amountDescending: self = .amountDescending
        case .amountAscending: self = .amountAscending
        }
    }

    var kit: DashKit.HistorySort {
        switch self {
        case .newestFirst: .newestFirst
        case .oldestFirst: .oldestFirst
        case .amountDescending: .amountDescending
        case .amountAscending: .amountAscending
        }
    }
}

extension WatchOnlyFilter {
    init(_ kit: DashKit.WatchOnlyFilter) {
        switch kit {
        case .all: self = .all
        case .yes: self = .yes
        case .no: self = .no
        }
    }

    var kit: DashKit.WatchOnlyFilter {
        switch self {
        case .all: .all
        case .yes: .yes
        case .no: .no
        }
    }
}

extension DisplayUnit {
    init(_ kit: DashKit.DisplayUnit) {
        switch kit {
        case .dash: self = .dash
        case .milliDash: self = .milliDash
        case .microDash: self = .microDash
        case .duffs: self = .duffs
        }
    }

    var kit: DashKit.DisplayUnit {
        switch self {
        case .dash: .dash
        case .milliDash: .milliDash
        case .microDash: .microDash
        case .duffs: .duffs
        }
    }
}

extension TxType {
    init(_ kit: DashKit.TxType) {
        switch kit {
        case .other: self = .other
        case .generated: self = .generated
        case .sendToAddress: self = .sendToAddress
        case .sendToOther: self = .sendToOther
        case .recvWithAddress: self = .recvWithAddress
        case .recvFromOther: self = .recvFromOther
        case .sendToSelf: self = .sendToSelf
        case .recvWithCoinJoin: self = .recvWithCoinJoin
        case .coinJoinMixing: self = .coinJoinMixing
        case .coinJoinCollateralPayment: self = .coinJoinCollateralPayment
        case .coinJoinMakeCollaterals: self = .coinJoinMakeCollaterals
        case .coinJoinCreateDenominations: self = .coinJoinCreateDenominations
        case .coinJoinSend: self = .coinJoinSend
        case .platformTransfer: self = .platformTransfer
        case .dustReceive: self = .dustReceive
        case .dataTransaction: self = .dataTransaction
        case .masternodeRegistration: self = .masternodeRegistration
        case .masternodeUpdate: self = .masternodeUpdate
        case .assetLock: self = .assetLock
        }
    }

    var kit: DashKit.TxType {
        switch self {
        case .other: .other
        case .generated: .generated
        case .sendToAddress: .sendToAddress
        case .sendToOther: .sendToOther
        case .recvWithAddress: .recvWithAddress
        case .recvFromOther: .recvFromOther
        case .sendToSelf: .sendToSelf
        case .recvWithCoinJoin: .recvWithCoinJoin
        case .coinJoinMixing: .coinJoinMixing
        case .coinJoinCollateralPayment: .coinJoinCollateralPayment
        case .coinJoinMakeCollaterals: .coinJoinMakeCollaterals
        case .coinJoinCreateDenominations: .coinJoinCreateDenominations
        case .coinJoinSend: .coinJoinSend
        case .platformTransfer: .platformTransfer
        case .dustReceive: .dustReceive
        case .dataTransaction: .dataTransaction
        case .masternodeRegistration: .masternodeRegistration
        case .masternodeUpdate: .masternodeUpdate
        case .assetLock: .assetLock
        }
    }
}

extension TxCategory {
    init(_ kit: DashKit.TxCategory) {
        switch kit {
        case .sent: self = .sent
        case .received: self = .received
        case .reward: self = .reward
        case .masternode: self = .masternode
        case .internalTransfer: self = .internalTransfer
        case .coinJoin: self = .coinJoin
        case .platform: self = .platform
        case .other: self = .other
        }
    }

    var kit: DashKit.TxCategory {
        switch self {
        case .sent: .sent
        case .received: .received
        case .reward: .reward
        case .masternode: .masternode
        case .internalTransfer: .internalTransfer
        case .coinJoin: .coinJoin
        case .platform: .platform
        case .other: .other
        }
    }
}

extension TxStatusKind {
    init(_ kit: DashKit.TxStatusKind) {
        switch kit {
        case .unconfirmed: self = .unconfirmed
        case .confirming: self = .confirming
        case .confirmed: self = .confirmed
        case .conflicted: self = .conflicted
        case .abandoned: self = .abandoned
        case .immature: self = .immature
        case .notAccepted: self = .notAccepted
        }
    }

    var kit: DashKit.TxStatusKind {
        switch self {
        case .unconfirmed: .unconfirmed
        case .confirming: .confirming
        case .confirmed: .confirmed
        case .conflicted: .conflicted
        case .abandoned: .abandoned
        case .immature: .immature
        case .notAccepted: .notAccepted
        }
    }
}
