//! Amount formatting and parsing with the rules of dash-qt's `BitcoinUnits`
//! (`src/qt/bitcoinunits.cpp`) and `GUIUtil::formatAmount`.
//!
//! Every function here produces the same string as the dash-qt function it
//! names. `testdata/amount_format.json` holds the vectors, generated by
//! running the dash-qt code against Qt 5.15 (`testdata/oracle/qt`).
//!
//! Rules that a reader might not expect:
//! - The thousands separator is U+2009 THIN SPACE, never a locale character.
//! - The decimal mark is always `.`.
//! - `floor_with_unit` and `format_amount` *truncate* decimals; they never round.
//! - Parsing ignores ASCII spaces and thin spaces anywhere in the input, and
//!   accepts one leading `+` or `-`.

/// Duffs per DASH.
pub const COIN: i64 = 100_000_000;

/// Largest valid amount, 21 million DASH (`MAX_MONEY` in Dash Core).
pub const MAX_MONEY: i64 = 21_000_000 * COIN;

/// U+2009 THIN SPACE, the thousands separator dash-qt uses.
pub const THIN_SP: char = '\u{2009}';

/// Width (in characters) that `justify` pads the integer part plus decimals to.
const MAX_DIGITS_BTC: usize = 16;

/// Longest string `parse` accepts after padding the decimals; longer input
/// could overflow 63 bits.
const MAX_PARSE_LEN: usize = 18;

/// A display unit. The discriminant is the index dash-qt stores in its
/// `nDisplayUnit` setting (DASH=0, mDASH=1, μDASH=2, duffs=3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Unit {
    Dash = 0,
    MilliDash = 1,
    MicroDash = 2,
    Duffs = 3,
}

/// Which family of unit names to use. dash-qt shows `tDASH`-style names on
/// every network except mainnet (testnet, devnet and regtest).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Chain {
    Main,
    Test,
}

/// Where thousands separators go.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SeparatorStyle {
    /// No separators.
    Never,
    /// Separators only when the integer part has more than four characters.
    Standard,
    /// Separators whenever the integer part has more than three characters.
    Always,
}

impl Unit {
    /// All units in dash-qt's menu order.
    pub const ALL: [Unit; 4] = [Unit::Dash, Unit::MilliDash, Unit::MicroDash, Unit::Duffs];

    /// The unit for a stored `nDisplayUnit` index.
    pub fn from_index(index: u8) -> Option<Unit> {
        Unit::ALL.get(usize::from(index)).copied()
    }

    /// The index dash-qt stores for this unit.
    pub fn index(self) -> u8 {
        self as u8
    }

    /// Duffs per one of this unit.
    pub fn factor(self) -> i64 {
        match self {
            Unit::Dash => 100_000_000,
            Unit::MilliDash => 100_000,
            Unit::MicroDash => 100,
            Unit::Duffs => 1,
        }
    }

    /// Number of decimals shown for this unit.
    pub fn decimals(self) -> usize {
        match self {
            Unit::Dash => 8,
            Unit::MilliDash => 5,
            Unit::MicroDash => 2,
            Unit::Duffs => 0,
        }
    }

    /// The unit's display name (`BitcoinUnits::name`). μ is U+03BC.
    pub fn name(self, chain: Chain) -> &'static str {
        match (self, chain) {
            (Unit::Dash, Chain::Main) => "DASH",
            (Unit::Dash, Chain::Test) => "tDASH",
            (Unit::MilliDash, Chain::Main) => "mDASH",
            (Unit::MilliDash, Chain::Test) => "mtDASH",
            (Unit::MicroDash, Chain::Main) => "\u{3bc}DASH",
            (Unit::MicroDash, Chain::Test) => "\u{3bc}tDASH",
            (Unit::Duffs, Chain::Main) => "duffs",
            (Unit::Duffs, Chain::Test) => "tduffs",
        }
    }
}

/// `BitcoinUnits::format`: the amount without a unit name.
///
/// `plus` prefixes `+` to positive amounts. `justify` left-pads the integer
/// part with spaces to `16 - decimals` characters before separators are
/// inserted (so padding spaces can be separated too, exactly as in dash-qt).
///
/// `i64::MIN` has no positive counterpart; dash-qt's behaviour for it is
/// undefined. Here its magnitude is computed without overflow.
pub fn format(
    unit: Unit,
    amount: i64,
    plus: bool,
    separators: SeparatorStyle,
    justify: bool,
) -> String {
    let coin = unit.factor().unsigned_abs();
    let num_decimals = unit.decimals();
    let n_abs = amount.unsigned_abs();
    let quotient = n_abs / coin;
    let mut quotient_str: Vec<char> = quotient.to_string().chars().collect();
    if justify {
        let width = MAX_DIGITS_BTC - num_decimals;
        if quotient_str.len() < width {
            let mut padded = vec![' '; width - quotient_str.len()];
            padded.extend(quotient_str);
            quotient_str = padded;
        }
    }

    let q_size = quotient_str.len();
    let separate = match separators {
        SeparatorStyle::Always => true,
        SeparatorStyle::Standard => q_size > 4,
        SeparatorStyle::Never => false,
    };
    if separate {
        // Same insertion order as the Qt loop: positions are counted from the
        // right on the unmodified length, so earlier inserts do not shift them.
        let mut i = 3;
        while i < q_size {
            quotient_str.insert(q_size - i, THIN_SP);
            i += 3;
        }
    }

    let mut out = String::with_capacity(quotient_str.len() + num_decimals + 3);
    if amount < 0 {
        out.push('-');
    } else if plus && amount > 0 {
        out.push('+');
    }
    out.extend(quotient_str);
    if num_decimals > 0 {
        let remainder = n_abs % coin;
        out.push('.');
        out.push_str(&format!("{remainder:0num_decimals$}"));
    }
    out
}

/// `BitcoinUnits::formatWithUnit`: `format` plus a space and the unit name.
pub fn format_with_unit(
    unit: Unit,
    amount: i64,
    plus: bool,
    separators: SeparatorStyle,
    chain: Chain,
) -> String {
    let mut s = format(unit, amount, plus, separators, false);
    s.push(' ');
    s.push_str(unit.name(chain));
    s
}

/// `BitcoinUnits::formatWithPrivacy`: right-justified amount with unit; when
/// `privacy` is on, the digits of a justified zero are replaced by `#`.
///
/// dash-qt asserts `amount >= 0`; this function formats negative amounts the
/// same way `format` does instead of aborting.
pub fn format_with_privacy(
    unit: Unit,
    amount: i64,
    separators: SeparatorStyle,
    privacy: bool,
    chain: Chain,
) -> String {
    let value = if privacy {
        format(unit, 0, false, separators, true).replace('0', "#")
    } else {
        format(unit, amount, false, separators, true)
    };
    format!("{value} {}", unit.name(chain))
}

/// `BitcoinUnits::floorWithUnit`: like `format_with_unit` but with the
/// decimals cut (not rounded) to `digits`. `digits` is dash-qt's "decimal
/// digits" display option (2–8 in the settings dialog).
pub fn floor_with_unit(
    unit: Unit,
    amount: i64,
    plus: bool,
    separators: SeparatorStyle,
    digits: usize,
    chain: Chain,
) -> String {
    let mut result = format(unit, amount, plus, separators, false);
    let decimals = unit.decimals();
    if decimals > digits {
        // `QString::chop`: the tail is ASCII digits (and the dot), so cutting
        // characters equals cutting UTF-16 units here.
        let chop = decimals - digits;
        let keep = result.chars().count().saturating_sub(chop);
        result = result.chars().take(keep).collect();
    }
    result.push(' ');
    result.push_str(unit.name(chain));
    result
}

/// `GUIUtil::formatAmount`: always-separated amount, optionally cut to
/// `truncate` decimals (`Some(0)` drops the dot too), then the unit name.
/// `signed` adds `+` to positive amounts.
pub fn format_amount(
    unit: Unit,
    amount: i64,
    signed: bool,
    truncate: Option<u8>,
    chain: Chain,
) -> String {
    let mut formatted = format(unit, amount, signed, SeparatorStyle::Always, false);
    if let Some(t) = truncate {
        // `indexOf('.')` / `left()` work on UTF-16 units; the dot index in
        // chars equals the index in UTF-16 units because every character
        // before it is in the BMP.
        let chars: Vec<char> = formatted.chars().collect();
        if let Some(dot) = chars.iter().position(|&c| c == '.') {
            let t = usize::from(t);
            if t == 0 {
                formatted = chars[..dot].iter().collect();
            } else if chars.len() > dot + 1 + t {
                formatted = chars[..dot + 1 + t].iter().collect();
            }
        }
    }
    format!("{formatted} {}", unit.name(chain))
}

/// `BitcoinUnits::parse`: a decimal string in `unit` to duffs.
///
/// Returns `None` exactly when dash-qt's parser returns false:
/// - empty input;
/// - more than one `.`;
/// - more decimals than the unit has;
/// - more than 18 characters (UTF-16 units) once decimals are padded;
/// - anything `QString::toLongLong` rejects. That accepts optional
///   whitespace at both ends of the padded string, one optional sign and at
///   least one ASCII digit.
///
/// Spaces (U+0020) and thin spaces (U+2009) are removed before anything else.
pub fn parse(unit: Unit, value: &str) -> Option<i64> {
    if value.is_empty() {
        return None;
    }
    let num_decimals = unit.decimals();
    let cleaned: String = value
        .chars()
        .filter(|&c| c != ' ' && c != THIN_SP)
        .collect();
    let parts: Vec<&str> = cleaned.split('.').collect();
    if parts.len() > 2 {
        return None;
    }
    let whole = parts[0];
    let decimals = parts.get(1).copied().unwrap_or("");
    let decimals_len = utf16_len(decimals);
    if decimals_len > num_decimals {
        return None;
    }
    let mut s = String::with_capacity(whole.len() + num_decimals);
    s.push_str(whole);
    s.push_str(decimals);
    for _ in decimals_len..num_decimals {
        s.push('0');
    }
    if utf16_len(&s) > MAX_PARSE_LEN {
        return None;
    }
    qt_to_long_long(&s)
}

fn utf16_len(s: &str) -> usize {
    s.chars().map(char::len_utf16).sum()
}

/// `QString::toLongLong(&ok)` in base 10 for strings of at most 18 UTF-16
/// units: whitespace (`QChar::isSpace`, the same set as Unicode White_Space)
/// is trimmed from both ends, then one optional sign and one or more ASCII
/// digits must make up the rest. Eighteen digits cannot overflow `i64`.
fn qt_to_long_long(s: &str) -> Option<i64> {
    let t = s.trim_matches(char::is_whitespace);
    let (negative, digits) = match t.as_bytes().first() {
        Some(b'+') => (false, &t[1..]),
        Some(b'-') => (true, &t[1..]),
        _ => (false, t),
    };
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    let magnitude: i64 = digits.parse().ok()?;
    Some(if negative { -magnitude } else { magnitude })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_indices_match_dash_qt_settings() {
        for (i, u) in Unit::ALL.iter().enumerate() {
            assert_eq!(usize::from(u.index()), i);
            assert_eq!(Unit::from_index(i as u8), Some(*u));
        }
        assert_eq!(Unit::from_index(4), None);
    }

    #[test]
    fn standard_separators_need_five_digits() {
        assert_eq!(
            format(
                Unit::Dash,
                1234 * COIN,
                false,
                SeparatorStyle::Standard,
                false
            ),
            "1234.00000000"
        );
        assert_eq!(
            format(
                Unit::Dash,
                12345 * COIN,
                false,
                SeparatorStyle::Standard,
                false
            ),
            "12\u{2009}345.00000000"
        );
        assert_eq!(
            format(
                Unit::Dash,
                1234 * COIN,
                false,
                SeparatorStyle::Always,
                false
            ),
            "1\u{2009}234.00000000"
        );
    }

    #[test]
    fn floor_truncates_instead_of_rounding() {
        assert_eq!(
            floor_with_unit(
                Unit::Dash,
                199_999_999,
                false,
                SeparatorStyle::Always,
                2,
                Chain::Main
            ),
            "1.99 DASH"
        );
    }

    #[test]
    fn parse_examples() {
        assert_eq!(parse(Unit::Dash, "0.001"), Some(100_000));
        assert_eq!(parse(Unit::Dash, "1,000"), None);
        assert_eq!(parse(Unit::Dash, "1\u{2009}000"), Some(1000 * COIN));
        assert_eq!(parse(Unit::Dash, "-1"), Some(-COIN));
        assert_eq!(parse(Unit::Duffs, "1\t"), Some(1));
        assert_eq!(parse(Unit::Dash, "1\t"), None);
    }

    #[test]
    fn i64_min_does_not_panic() {
        assert_eq!(
            format(Unit::Dash, i64::MIN, false, SeparatorStyle::Never, false),
            "-92233720368.54775808"
        );
    }
}
